-- 系统表结构文件
-- 1、客服管理系统
-- Drop table

-- DROP TABLE staffadmin.shunt;

CREATE TABLE staffadmin.shunt (
                                  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  created_by varchar(500) NOT NULL,
                                  created_date timestamp NOT NULL,
                                  last_modified_by varchar(500) NULL,
                                  last_modified_date timestamp NULL,
                                  organization_id int4 NOT NULL,
                                  "name" varchar(250) NULL,
                                  shunt_class_id int8 NULL,
                                  code varchar(500) NULL,
                                  CONSTRAINT shunt_pkey PRIMARY KEY (id)
);
CREATE INDEX shunt_name_idx ON staffadmin.shunt USING btree (name);
CREATE INDEX shunt_organization_id_idx ON staffadmin.shunt USING btree (organization_id);


-- Drop table

-- DROP TABLE staffadmin.shunt_class;

CREATE TABLE staffadmin.shunt_class (
                                        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        created_by varchar(500) NOT NULL,
                                        created_date timestamp NOT NULL,
                                        last_modified_by varchar(500) NULL,
                                        last_modified_date timestamp NULL,
                                        organization_id int4 NOT NULL,
                                        class_name varchar(250) NULL,
                                        catalogue int8 NULL,
                                        CONSTRAINT shunt_class_pkey PRIMARY KEY (id)
);
CREATE INDEX shunt_class_class_name_idx ON staffadmin.shunt_class USING btree (class_name);
CREATE INDEX shunt_class_organization_id_idx ON staffadmin.shunt_class USING btree (organization_id);

-- Drop table

-- DROP TABLE staffadmin.staff;

CREATE TABLE staffadmin.staff (
                                  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  created_by varchar(500) NOT NULL,
                                  created_date timestamp NOT NULL,
                                  last_modified_by varchar(500) NULL,
                                  last_modified_date timestamp NULL,
                                  organization_id int4 NULL,
                                  username varchar(250) NULL,
                                  "password" varchar(250) NULL,
                                  "role" varchar(50) NULL,
                                  staff_group_id int8 NULL,
                                  real_name varchar(250) NULL,
                                  nick_name varchar(250) NULL,
                                  simultaneous_service int2 NULL,
                                  max_ticket_per_day int2 NULL,
                                  max_ticket_all_time int2 NULL,
                                  staff_type int2 NULL,
                                  gender int2 NULL,
                                  mobile_phone varchar(50) NULL,
                                  personalized_signature varchar(500) NULL,
                                  CONSTRAINT staff_group_pkey PRIMARY KEY (id)
);
CREATE INDEX staff_organization_id_idx ON staffadmin.staff USING btree (organization_id);
CREATE INDEX staff_organization_id_name_idx ON staffadmin.staff USING btree (organization_id, username);
CREATE INDEX staff_staff_group_id_idx ON staffadmin.staff USING btree (staff_group_id);

-- Drop table

-- DROP TABLE staffadmin.staff_config;

CREATE TABLE staffadmin.staff_config (
                                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         created_by varchar(500) NOT NULL,
                                         created_date timestamp NOT NULL,
                                         last_modified_by varchar(500) NULL,
                                         last_modified_date timestamp NULL,
                                         organization_id int4 NULL,
                                         staff_id int4 NULL,
                                         shunt_id int4 NULL,
                                         priority int2 NULL,
                                         CONSTRAINT staff_config_group_pkey PRIMARY KEY (id)
);
CREATE INDEX staff_config_shunt_id_name_idx ON staffadmin.staff_config USING btree (shunt_id);
CREATE INDEX staff_config_staff_id_idx ON staffadmin.staff_config USING btree (staff_id);


-- Drop table

-- DROP TABLE staffadmin.staff_group;

CREATE TABLE staffadmin.staff_group (
                                        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        created_by varchar(500) NOT NULL,
                                        created_date timestamp NOT NULL,
                                        last_modified_by varchar(500) NULL,
                                        last_modified_date timestamp NULL,
                                        organization_id int4 NULL,
                                        group_name varchar(250) NULL,
                                        CONSTRAINT staff_group_pkey PRIMARY KEY (id)
);
CREATE INDEX staff_group_group_name_idx ON staffadmin.staff_group USING btree (group_name);
CREATE INDEX staff_group_organization_id_idx ON staffadmin.staff_group USING btree (organization_id);
