-- 系统表结构文件
-- 1、客服管理系统
-- Drop table

-- DROP TABLE staffadmin.shunt;

CREATE TABLE staffadmin.shunt
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    organization_id    int4         NOT NULL,
    "name"             varchar(250) NULL,
    shunt_class_id     int8 NULL,
    code               varchar(500) NULL,
    CONSTRAINT shunt_pkey PRIMARY KEY (id)
);
CREATE
INDEX shunt_name_idx ON staffadmin.shunt USING btree (name);
CREATE
INDEX shunt_organization_id_idx ON staffadmin.shunt USING btree (organization_id);
create
index shunt_code_index on staffadmin.shunt using btree (code);

-- Drop table

-- DROP TABLE staffadmin.shunt_class;

CREATE TABLE staffadmin.shunt_class
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    organization_id    int4         NOT NULL,
    class_name         varchar(250) NULL,
    catalogue          int8 NULL,
    CONSTRAINT shunt_class_pkey PRIMARY KEY (id)
);
CREATE
INDEX shunt_class_class_name_idx ON staffadmin.shunt_class USING btree (class_name);
CREATE
INDEX shunt_class_organization_id_idx ON staffadmin.shunt_class USING btree (organization_id);

-- Drop table

-- DROP TABLE staffadmin.staff;

CREATE TABLE staffadmin.staff
(
    id                     int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by             varchar(500) NOT NULL,
    created_date           timestamp    NOT NULL,
    last_modified_by       varchar(500) NULL,
    last_modified_date     timestamp NULL,
    organization_id        int4 NULL,
    username               varchar(250) NULL,
    "password"             varchar(250) NULL,
    "role"                 varchar(50) NULL,
    staff_group_id         int8 NULL,
    real_name              varchar(250) NULL,
    nick_name              varchar(250) NULL,
    avatar                 varchar(250) NULL,
    simultaneous_service   int2 NULL,
    max_ticket_per_day     int2 NULL,
    max_ticket_all_time    int2 NULL,
    staff_type             int2 NULL,
    gender                 int2 NULL,
    mobile_phone           varchar(50) NULL,
    personalized_signature varchar(500) NULL,
    enabled                boolean default true,
    CONSTRAINT staff_group_pkey PRIMARY KEY (id)
);
CREATE
INDEX staff_organization_id_idx ON staffadmin.staff USING btree (organization_id);
CREATE
INDEX staff_organization_id_name_idx ON staffadmin.staff USING btree (organization_id, username);
CREATE
INDEX staff_staff_group_id_idx ON staffadmin.staff USING btree (staff_group_id);
create
index staff_enabled on staffadmin.staff USING btree (enabled);
create
index staff_staff_type on staffadmin.staff using btree (staff_type);

-- Drop table

-- DROP TABLE staffadmin.staff_config;

CREATE TABLE staffadmin.staff_config
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    organization_id    int4 NULL,
    staff_id           int4 NULL,
    shunt_id           int4 NULL,
    priority           int2 NULL,
    CONSTRAINT staff_config_group_pkey PRIMARY KEY (id)
);
CREATE
INDEX staff_config_shunt_id_name_idx ON staffadmin.staff_config USING btree (shunt_id);
CREATE
INDEX staff_config_staff_id_idx ON staffadmin.staff_config USING btree (staff_id);


-- Drop table

-- DROP TABLE staffadmin.staff_group;

CREATE TABLE staffadmin.staff_group
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    organization_id    int4 NULL,
    group_name         varchar(250) NULL,
    CONSTRAINT staff_group_pkey PRIMARY KEY (id)
);
CREATE
INDEX staff_group_group_name_idx ON staffadmin.staff_group USING btree (group_name);
CREATE
INDEX staff_group_organization_id_idx ON staffadmin.staff_group USING btree (organization_id);


-- Drop table

-- DROP TABLE staffadmin.shunt_ui_config;

CREATE TABLE staffadmin.shunt_ui_config
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id    int4 NULL,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    shunt_id           int8 NULL,
    config             varchar(2000) NULL,
    CONSTRAINT shunt_ui_config_pkey PRIMARY KEY (id)
);
CREATE
INDEX shunt_ui_config_shunt_id ON staffadmin.shunt_ui_config USING btree (shunt_id);
CREATE
INDEX shunt_ui_config_organization_id_idx ON staffadmin.shunt_ui_config USING btree (organization_id);


-- Drop table

-- DROP TABLE bot.shunt_ui_config;

CREATE TABLE bot.bot_config
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id    int4 NULL,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    bot_id             int8         NOT NULL,
    knowledge_base_id  int8         NOT NULL,
    no_answer_reply    varchar(500) NOT NULL,
    CONSTRAINT bot_config_pkey PRIMARY KEY (id)
);
CREATE
UNIQUE INDEX bot_config_bot_id_idx ON bot.bot_config USING btree (bot_id);
CREATE
INDEX bot_config_knowledge_base_id_idx ON bot.bot_config USING btree (knowledge_base_id);
CREATE
INDEX bot_config_organization_id_idx ON bot.bot_config USING btree (organization_id);


CREATE TABLE bot.knowledge_base
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id    int4 NULL,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    name               varchar(250) NOT NULL,
    description        varchar(250) NOT NULL,
    CONSTRAINT knowledge_base_pkey PRIMARY KEY (id)
);

CREATE
INDEX knowledge_base_organization_id_idx ON bot.knowledge_base USING btree (organization_id);


CREATE TABLE bot.topic_category
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id    int4 NULL,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    name               varchar(250) NOT NULL,
    pid                int8 NULL,
    CONSTRAINT topic_category_pkey PRIMARY KEY (id)
);

CREATE
INDEX topic_category_organization_id_idx ON bot.topic_category USING btree (organization_id);
CREATE
INDEX topic_category_pid_idx ON bot.topic_category USING btree (pid);


CREATE TABLE dispathcer.customer
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_id    int4 NULL,
    created_by         varchar(500) NOT NULL,
    created_date       timestamp    NOT NULL,
    last_modified_by   varchar(500) NULL,
    last_modified_date timestamp NULL,
    uid                varchar(100) NOT NULL,
    name               varchar(50) NULL,
    email              varchar(50) NULL,
    mobile             varchar(50) NULL,
    vip_level          int4 NULL,
    CONSTRAINT topic_category_pkey PRIMARY KEY (id)
);

CREATE
INDEX customer_organization_id_idx ON dispathcer.customer USING btree (organization_id);
CREATE
INDEX customer_uid_idx ON dispathcer.customer USING btree (uid);