package com.qingzhu.common.domain

import com.fasterxml.jackson.annotation.JsonIgnore
import org.springframework.data.annotation.CreatedBy
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedBy
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import java.io.Serializable
import java.time.Instant
import javax.persistence.Column
import javax.persistence.EntityListeners
import javax.persistence.MappedSuperclass

/**
 * DDL
CREATE TABLE xxx (
id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
created_by varchar(500) NOT NULL,
created_date timestamp NOT NULL,
last_modified_by varchar(500) NULL,
last_modified_date timestamp NULL,
CONSTRAINT staff_group_pkey PRIMARY KEY (id)
);
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener::class)
abstract class AbstractAuditingEntity : Serializable {
    companion object {
        @JvmStatic
        private val serialVersionUID = 1L
    }

    @CreatedBy
    @Column(name = "created_by", nullable = false, length = 50, updatable = false)
    @JsonIgnore
    var createdBy: String? = null

    @CreatedDate
    @Column(name = "created_date", updatable = false)
    @JsonIgnore
    var createdDate = Instant.now()

    @LastModifiedBy
    @Column(name = "last_modified_by", length = 50)
    @JsonIgnore
    var lastModifiedBy: String? = null

    @LastModifiedDate
    @Column(name = "last_modified_date")
    @JsonIgnore
    var lastModifiedDate = Instant.now()

    /** 机构 ID **/
    var organizationId: Int? = null
}

@MappedSuperclass
abstract class AbstractStaffEntity : AbstractAuditingEntity() {
    // 配置的客服 (每个客服可以有多个配置)
    /** @ManyToOne */
    var staffId: Long? = null
}