server:
  port: 9191

spring:
  application:
    name: message-server

  redis:
    database: 0
    host: 10.0.0.100
    port: 6379
    password: test123
    timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.0.101:5432/postgres?currentSchema=message
    username: postgres
    password: 5CPKuFFTyZ

  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: http://localhost:8000/.well-known/jwks.json

  cloud:
    inetutils:
      ignored-interfaces:
        - eth*
      preferred-networks:
        - 10.0.*
    consul:
      host: 10.0.0.105
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
        # health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    loadbalancer:
      ribbon:
        enabled: false

    stream:
      function:
        definition: message;inKStreamProcess;outKStreamProcess
      poller:
        fixed-delay: 500
        max-messages-per-poll: 1
      kafka:
        binder:
          brokers: 10.0.0.109:9092
        streams:
          binder:
            functions:
              message:
                applicationId: message
              inKStreamProcess:
                applicationId: inKStreamProcess
              outKStreamProcess:
                applicationId: outKStreamProcess
      bindings:
        message-out-0:
          destination: im.test
        outKStreamProcess-in-0:
          destination: im.test
        outKStreamProcess-out-0:
          destination: im.message
        inKStreamProcess-in-0:
          destination: im.message

  security:
    oauth2:
      client:
        provider:
          authProvider:
            token-uri: http://oauth2-auth-server/oauth/token
        registration:
          authProvider:
            client-id: inner_client
            client-secret: test_secret
            authorization-grant-type: client_credentials
logging:
  level:
    root: info
