###
# 测试 token
GET http://localhost:9090/websocket-address
Accept: */*
Cache-Control: no-cache
# base64 of user_client:test_secret
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6OTQ5MSwiYXVkIjpbImNzLWFkbWluIiwiaW0iLCJib3QiLCJvYXV0aDIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJ0ZXN0Il0sImV4cCI6MTU4NDk2NjMyNCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI0ZjFhZWMyNy04ZWJjLTRhM2EtODcwNy1jYTJmNjA1NzljNjIiLCJjbGllbnRfaWQiOiJ1c2VyX2NsaWVudCJ9.EpWOoVyk1j-H5p9uTpqOOZFMhyRc9gQPSe7j9HiRX8PQBUtQFs_lUeWhLUuU_ZRhI6QsaqIFV_M4VSD8GI7hGH56qkNd1hib0DFhxWBoyWn1FuTw7pINtYxHNQG87K3ncZ5a5oFvx6krdTdj7leu2s_iZ32QheRLcji1XGNF951Wl_Ip-4jnhesmWi4oYVHKRwrJ-MGWAw4RwWmSrZEMvl8HE3W68tSdGTnw-H1_k4rvD0tJlWxE6mDpEgj-xkQvNKjRbMNXT19YYQ7TNWzd4SjdQKK0CxZdjIAholvo3g8VPoKNxM81IYHl2_UFBTETbbk9wb5-Ol34OXB7kiqXLA

###
