package com.qingzhu.messageserver.domain.entity

import com.qingzhu.common.constant.NoArg


/**
 * ChatMessage entity
 */
@NoArg
data class ChatMessage(
        /** Ordered ID generated by the server */
        val seqId: Long,
        /** The client generates the chat message id */
        var msgId: Long
)