package com.qingzhu.staffadmin.staff.domain.entity

import com.qingzhu.common.domain.AbstractAuditingEntity
import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Table

/**
 * 接待组 aka 技能组
 *
 * create sql
 *
-- Drop table

-- DROP TABLE staffadmin.shunt;

CREATE TABLE staffadmin.shunt (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code varchar(255) NULL,
    "name" varchar(255) NULL,
    organization_id int4 NOT NULL,
    shunt_class_id int8 NOT NULL,
    created_by varchar(500) NOT NULL,
    created_date timestamp NOT NULL,
    last_modified_by varchar(500) NULL,
    last_modified_date timestamp NULL,
    CONSTRAINT shunt_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_org ON staffadmin.shunt USING btree (organization_id);
CREATE INDEX idx_shunt_class ON staffadmin.shunt USING btree (shunt_class_id);
 *
 */
@Table
data class Shunt(
        // 公司id
        val organizationId: Int,
        // 接待组 名称
        val name: String,
        // 接待组所属分类
        // @ManyToOne
        val shuntClassId: Long,
        // 接待组范围代码
        val code: String
) : AbstractAuditingEntity() {
    @Id
    var id: Long? = null
}